// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/blogs": {
    params: {};
  };
  "/blogs/:slug": {
    params: {
      "slug": string;
    };
  };
  "/projects": {
    params: {};
  };
  "/contact": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/blogs" | "/blogs/:slug" | "/projects" | "/contact";
  };
  "./pages/Home.tsx": {
    id: "pages/Home";
    page: "/";
  };
  "./pages/About.tsx": {
    id: "pages/About";
    page: "/about";
  };
  "./pages/Blogs.tsx": {
    id: "pages/Blogs";
    page: "/blogs";
  };
  "./pages/BlogDetail.tsx": {
    id: "pages/BlogDetail";
    page: "/blogs/:slug";
  };
  "./pages/Projects.tsx": {
    id: "pages/Projects";
    page: "/projects";
  };
  "./pages/Contact.tsx": {
    id: "pages/Contact";
    page: "/contact";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "pages/Home": typeof import("./src/./pages/Home.tsx");
  "pages/About": typeof import("./src/./pages/About.tsx");
  "pages/Blogs": typeof import("./src/./pages/Blogs.tsx");
  "pages/BlogDetail": typeof import("./src/./pages/BlogDetail.tsx");
  "pages/Projects": typeof import("./src/./pages/Projects.tsx");
  "pages/Contact": typeof import("./src/./pages/Contact.tsx");
};